---
# tasks file for java

- name: Set JRE version
  shell:  'curl -s https://java.com/en/download/linux_manual.jsp | grep "Recommended Version" | cut -d " " -f 4'
  register: java_version
  
- name: Set JRE update
  shell: 'curl -s https://java.com/en/download/linux_manual.jsp | grep "Recommended Version" | cut -d " " -f 6 | cut -d "<" -f 1'
  register: java_update

- name: Set JRE download link
  shell: 'curl -s https://java.com/en/download/linux_manual.jsp | grep "Download Java software for Linux x64" | cut -d "\"" -f 4 | head -1'
  register: java_tar_url

- name: download jre tar file
  get_url:
    url: "{{ java_tar_url.stdout }}"
    dest: /tmp/{{ java_tar_file }}
#
- name: unarchive java tar
  unarchive:
    src: /tmp/{{ java_tar_file }}
    dest: /opt
    copy: no 

- name: Rename jar directory
  command: "mv /opt/jre1.{{java_version.stdout}}.0_{{ java_update.stdout}} {{ java_dir }}"

- name: correct java version selected
  alternatives:
    name: java
    path: /opt/jre/bin/java
    link: /usr/bin/java
