--- # Pre install server configuration

#- name: Disabling SELinux
#  lineinfile:
#    path: /etc/selinux/config
#    regexp: '^SELINUX='
#    line: 'SELINUX=disabled'
- name: Disabling SELinux
  selinux: 
    state: disabled
    policy: targeted
  when: ansible_selinux.status == "enabled"
#- name: Stop and disable Firewalld.
#  service:
#    name: firewalld
#    state: stopped
#    enabled: no
- name: Remove firewalld
  package:
    name: firewalld
    state: absent
- name: Install iptables
  package: 
    name: iptables-services
    state: latest
- name: Start and Enable iptables
  service:
    name: iptables
    state: restarted
    enabled: yes
- name: Open ssh, http, https, mysql port 
  lineinfile:
    path: /etc/sysconfig/iptables
    regexp: '-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
    line: "-A INPUT -p tcp -m state --state NEW -m tcp --dport 2222 -j ACCEPT\n
            -A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT\n
            -A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT\n
            -A INPUT -p tcp -m state --state NEW -m tcp --dport 3306 -j ACCEPT"
